title: My GitHub Page
description: This is my awesome hacker-themed GitHub Pages site.
theme: jekyll-theme-hacker

# Optional settings:
# Set your GitHub repository URL if you want to display "View on GitHub"
github:
  is_project_page: false
  repository_url: https://github.com/ray-seal/practice-html

# Optional: Google Analytics, social links, etc.
# google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown